language: ruby
rvm:
  - 2.7.0
cache: bundler
before_install: cp config/database.yml.example config/database.yml
script:
  - bin/rails db:setup RAILS_ENV=test
  - bundle exec rspec --format doc
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
services:
  - postgresql
env:
  global:
    - COVERAGE=true
    - RAILS_ENV=test
