language: ruby
rvm:
  - 2.7.0
cache: bundler
before_install: cp config/database.yml.example config/database.yml
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec --format doc
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
addons:
  postgresql: 9.3
env:
  global:
    - COVERAGE=true
    - RAILS_ENV=test
