# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:
  password:

development:
  <<: *default
  database: vayne_development_database

test:
  <<: *default
  database: vayne_test_database

production:
  <<: *default
  database: vayne_production_database
